export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const GET_PRODUCT_START = "GET_PRODUCT_START";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";
